// SPDX-License-Identifier: GPL-3.0-or-later
/* ==========================================================================
   trk! mmd.js — 🩷 MMDマスコット（PMX/PMD モデル ＋ VMD モーション）
   ・Lat式ミク・タワシ式CHAN×CO など、MMDのモデルを「自分の端末から」読み込んで動かせます。
     モデルは同梱しません（配布元の規約にしたがって、各自が用意してください）。
   ・3Dの部品（three.js / @yohawing/three-mmd-loader）は、MMDを初めて使うときだけ
     index.html の importmap から読み込みます（CDN。オフラインでは使えません）。
   ・モーションは2つの道：
     ① 自分で用意した .vmd を読み込む（配布元の規約を確認してから）
     ② 内蔵モーション（このファイルがコードで VMD を組み立てます＝自作なので権利は trk! のもの）
   ・物理（髪・スカートの揺れ）は、ライブラリの対応範囲ですが、いまはオフ（軽さ優先）。
   読み込み順：… → vrm.js → mmd.js（どちらも遅延読み込みの3D）   ※ vrm.js とは独立しています。
   ========================================================================== */
"use strict";
(() => {
const MB = 1048576, MAX_PMX = 120 * MB, MAX_VMD = 40 * MB, MAX_FILES = 400;
const MMD_LIB = "@yohawing/three-mmd-loader";
const mmdDB = idbStore("shadow_taiko_mmd", "files");     // 🆕 新しい保存先（既存のキーは変えません）

/* ============ 文章（接頭辞 mmd…） ============ */
Object.assign(TEXT.ja, {
  mmdTitle:"🩷 MMD（モデルは自分で用意）",
  mmdHint:"MMDのモデル（.pmx/.pmd）とモーション（.vmd）を読み込んで、ゲーム中に踊らせられます。モデルは同梱していません。配布元の規約（商用不可・再配布不可など）を守って、自分で用意してください。",
  mmdAgree:"配布元の規約を確認し、自分で用意したモデルを使います（三次配布・商用利用はしません）",
  mmdChooseModel:"📦 モデル（.pmx/.pmd）", mmdChooseFolder:"📁 モデルのフォルダ（テクスチャも一緒に）",
  mmdChooseMotion:"🎬 モーション（.vmd）", mmdClearModel:"モデルを外す", mmdClearMotion:"モーションを外す",
  mmdRemember:"読み込んだモデル・モーションを、この端末に保存する（IndexedDB）",
  mmdModelHead:"モデル", mmdMotionHead:"モーション", mmdFitHead:"大きさ・向き",
  mmdSize:"大きさ", mmdTurn:"向き（左右）", mmdCreditLabel:"クレジット表示（作者名など）", mmdCreditPlaceholder:"例：Lat式ミク / Lat",
  mmdMotionNone:"（モーションなし）",
  mmdMotionStep:"内蔵① ステップ（120BPM）", mmdMotionSwing:"内蔵② ゆらゆら（100BPM）", mmdMotionTurn:"内蔵③ ターン（120BPM）",
  mmdBuiltinNote:"内蔵モーションは trk! がコードで作った VMD です（権利は trk! のもの）。曲のBPMに合わせて速さを変えられます。",
  mmdBpm:"モーションの基準BPM（曲に合わせる・0で固定）",
  mmdLoading:"モデルを読み込んでいます…", mmdLoadingPct:"モデルを読み込んでいます… {n}%",
  mmdLoaded:"モデル「{name}」を読み込みました。", mmdRestored:"前回のモデルを戻しました。",
  mmdNotMmd:"MMDのモデル（.pmx/.pmd）ではありません。", mmdTooBig:"大きすぎます（モデルは{n}MB、モーションは{m}MBまで）。",
  mmdNoModel:"先にモデルを読み込んでください。", mmdNetError:"3Dの部品（CDN）を読み込めませんでした。オンラインで開いて、もう一度試してください。",
  mmdNoWebGL:"WebGLを使えない環境です。", mmdLoadError:"モデルを読み込めませんでした。",
  mmdNoAgree:"先に、うえの「規約を確認しました」にチェックを入れてください。",
  mmdFilesEmpty:"モデルのファイルが入っていません。", mmdTooManyFiles:"ファイルが多すぎます（{n}個まで）。",
  mmdVmdLoaded:"モーション「{name}」を読み込みました。", mmdVmdBad:"VMD（モーション）ではありません／読み込めませんでした。",
  mmdSelected:"MMDのマスコットに切り替えました。", mmdSafe:"🛟 セーフモード中は、MMDの読み込み・復元をしません。",
  mmdSaveFail:"この端末に保存できませんでした（大きすぎる可能性があります）。",
  mmdCreditPrefix:"MMD:"
});
Object.assign(TEXT.en, {
  mmdTitle:"🩷 MMD (bring your own model)",
  mmdHint:"Load an MMD model (.pmx/.pmd) and motion (.vmd) and let it dance in-game. No models are bundled — get your own and follow the distributor's terms (usually non-commercial, no redistribution).",
  mmdAgree:"I'll use a model I obtained myself, following its terms (no re-distribution, no commercial use)",
  mmdChooseModel:"📦 Model (.pmx/.pmd)", mmdChooseFolder:"📁 Model folder (with textures)",
  mmdChooseMotion:"🎬 Motion (.vmd)", mmdClearModel:"Remove model", mmdClearMotion:"Remove motion",
  mmdRemember:"Keep the loaded model and motion on this device (IndexedDB)",
  mmdModelHead:"Model", mmdMotionHead:"Motion", mmdFitHead:"Size and angle",
  mmdSize:"Size", mmdTurn:"Facing", mmdCreditLabel:"Credit line (author etc.)", mmdCreditPlaceholder:"e.g. Lat-style Miku / Lat",
  mmdMotionNone:"(no motion)",
  mmdMotionStep:"Built-in 1: Step (120 BPM)", mmdMotionSwing:"Built-in 2: Sway (100 BPM)", mmdMotionTurn:"Built-in 3: Turn (120 BPM)",
  mmdBuiltinNote:"The built-in motions are VMD data generated by trk!'s own code. They can speed up or slow down to the song's BPM.",
  mmdBpm:"Motion base BPM (follow the song; 0 = fixed)",
  mmdLoading:"Loading the model…", mmdLoadingPct:"Loading the model… {n}%",
  mmdLoaded:"Loaded the model “{name}”.", mmdRestored:"Restored your previous model.",
  mmdNotMmd:"That is not an MMD model (.pmx/.pmd).", mmdTooBig:"Too big (models up to {n}MB, motions up to {m}MB).",
  mmdNoModel:"Load a model first.", mmdNetError:"Could not load the 3D parts (CDN). Open it online and try again.",
  mmdNoWebGL:"WebGL is not available here.", mmdLoadError:"Could not load the model.",
  mmdNoAgree:"Tick “I'll use a model I obtained myself” above first.",
  mmdFilesEmpty:"No files in that folder.", mmdTooManyFiles:"Too many files (up to {n}).",
  mmdVmdLoaded:"Loaded the motion “{name}”.", mmdVmdBad:"That is not a VMD motion, or it could not be read.",
  mmdSelected:"Switched to the MMD mascot.", mmdSafe:"🛟 Safe mode: MMD loading and restore are off.",
  mmdSaveFail:"Could not save on this device (it may be too big).",
  mmdCreditPrefix:"MMD:"
});
Object.assign(TEXT.zh, {
  mmdTitle:"🩷 MMD（模型请自己准备）",
  mmdHint:"可以读取MMD模型（.pmx/.pmd）和动作（.vmd），让其在游戏中跳舞。本应用不附带模型，请遵守发布方的规约，自行准备（多为禁止商用、禁止再分发）。",
  mmdAgree:"我会遵守发布方的规约，使用自己准备的模型（不再分发、不商用）",
  mmdChooseModel:"📦 模型（.pmx/.pmd）", mmdChooseFolder:"📁 模型文件夹（含贴图）",
  mmdChooseMotion:"🎬 动作（.vmd）", mmdClearModel:"移除模型", mmdClearMotion:"移除动作",
  mmdRemember:"把读取的模型和动作保存在本机（IndexedDB）",
  mmdModelHead:"模型", mmdMotionHead:"动作", mmdFitHead:"大小与朝向",
  mmdSize:"大小", mmdTurn:"朝向", mmdCreditLabel:"署名显示（作者等）", mmdCreditPlaceholder:"例：Lat式ミク / Lat",
  mmdMotionNone:"（无动作）",
  mmdMotionStep:"内置① 踏步（120BPM）", mmdMotionSwing:"内置② 摇摆（100BPM）", mmdMotionTurn:"内置③ 转身（120BPM）",
  mmdBuiltinNote:"内置动作是由 trk! 自行用代码生成的 VMD。可按歌曲的BPM改变速度。",
  mmdBpm:"动作基准BPM（跟随歌曲・0 为固定）",
  mmdLoading:"正在读取模型…", mmdLoadingPct:"正在读取模型… {n}%",
  mmdLoaded:"已读取模型「{name}」。", mmdRestored:"已恢复上次的模型。",
  mmdNotMmd:"这不是MMD模型（.pmx/.pmd）。", mmdTooBig:"太大（模型上限 {n}MB，动作上限 {m}MB）。",
  mmdNoModel:"请先读取模型。", mmdNetError:"无法读取3D部件（CDN）。请联网后重试。",
  mmdNoWebGL:"此环境无法使用 WebGL。", mmdLoadError:"无法读取模型。",
  mmdNoAgree:"请先勾选上面的「已确认规约」。",
  mmdFilesEmpty:"文件夹里没有文件。", mmdTooManyFiles:"文件太多（最多 {n} 个）。",
  mmdVmdLoaded:"已读取动作「{name}」。", mmdVmdBad:"不是VMD动作，或无法读取。",
  mmdSelected:"已切换到MMD吉祥物。", mmdSafe:"🛟 安全模式下不会读取・恢复MMD。",
  mmdSaveFail:"无法保存到本机（可能太大）。",
  mmdCreditPrefix:"MMD:"
});
Object.assign(TEXT.ko, {
  mmdTitle:"🩷 MMD (모델은 직접 준비)",
  mmdHint:"MMD 모델(.pmx/.pmd)과 모션(.vmd)을 불러와 게임 중에 춤추게 할 수 있습니다. 모델은 동봉하지 않습니다. 배포처의 규약(비상업・재배포 금지 등)을 지켜 직접 준비해 주세요.",
  mmdAgree:"배포처의 규약을 확인하고, 직접 준비한 모델을 사용합니다 (재배포・상업 이용 안 함)",
  mmdChooseModel:"📦 모델 (.pmx/.pmd)", mmdChooseFolder:"📁 모델 폴더 (텍스처 포함)",
  mmdChooseMotion:"🎬 모션 (.vmd)", mmdClearModel:"모델 빼기", mmdClearMotion:"모션 빼기",
  mmdRemember:"불러온 모델・모션을 이 기기에 저장 (IndexedDB)",
  mmdModelHead:"모델", mmdMotionHead:"모션", mmdFitHead:"크기・방향",
  mmdSize:"크기", mmdTurn:"방향", mmdCreditLabel:"크레딧 표시 (제작자 등)", mmdCreditPlaceholder:"예: Lat式ミク / Lat",
  mmdMotionNone:"(모션 없음)",
  mmdMotionStep:"내장① 스텝 (120BPM)", mmdMotionSwing:"내장② 흔들흔들 (100BPM)", mmdMotionTurn:"내장③ 턴 (120BPM)",
  mmdBuiltinNote:"내장 모션은 trk!가 코드로 만든 VMD입니다. 곡의 BPM에 맞춰 속도를 바꿀 수 있습니다.",
  mmdBpm:"모션 기준 BPM (곡에 맞춤・0이면 고정)",
  mmdLoading:"모델을 불러오는 중…", mmdLoadingPct:"모델을 불러오는 중… {n}%",
  mmdLoaded:"모델 '{name}'을(를) 불러왔습니다.", mmdRestored:"지난번 모델을 되돌렸습니다.",
  mmdNotMmd:"MMD 모델(.pmx/.pmd)이 아닙니다.", mmdTooBig:"너무 큽니다 (모델 {n}MB, 모션 {m}MB까지).",
  mmdNoModel:"먼저 모델을 불러와 주세요.", mmdNetError:"3D 부품(CDN)을 불러오지 못했습니다. 온라인에서 다시 시도해 주세요.",
  mmdNoWebGL:"WebGL을 쓸 수 없는 환경입니다.", mmdLoadError:"모델을 불러오지 못했습니다.",
  mmdNoAgree:"위의 '규약을 확인했습니다'를 먼저 체크해 주세요.",
  mmdFilesEmpty:"폴더에 파일이 없습니다.", mmdTooManyFiles:"파일이 너무 많습니다 ({n}개까지).",
  mmdVmdLoaded:"모션 '{name}'을(를) 불러왔습니다.", mmdVmdBad:"VMD 모션이 아니거나 읽을 수 없습니다.",
  mmdSelected:"MMD 마스코트로 바꿨습니다.", mmdSafe:"🛟 안전 모드에서는 MMD 읽기・복원을 하지 않습니다.",
  mmdSaveFail:"이 기기에 저장하지 못했습니다 (너무 클 수 있습니다).",
  mmdCreditPrefix:"MMD:"
});

/* ============ 小さな道具 ============ */
const status = (k, v) => setStatus("mmdStatus", k, v);
const mmdRect = () => VRM_RECT[settings.layout] || VRM_RECT.classic;
const safeNow = () => { try { return typeof window.TrkSafeMode === "function" && window.TrkSafeMode(); } catch (_) { return false; } };
const isMmdFile = n => /\.(pmx|pmd)$/i.test(String(n || ""));
const isVmdFile = n => /\.vmd$/i.test(String(n || ""));
let chain = Promise.resolve();
const enqueue = fn => (chain = chain.then(fn).catch(e => console.error(e)));
const fail = key => { const e = new Error(key); e.key = key; return e; };

/* ============ 📼 内蔵モーション：VMD（Shift-JIS）を自分で組み立てる ============
   VMDは、ボーン名をShift-JISで15バイトに詰めた、素直なバイナリです。
   使う文字だけ表に持てば足ります（ここにあるのは、規格のための事実データです）。 */
const SJIS = {
  "セ":[0x83,0x5a], "ン":[0x83,0x93], "タ":[0x83,0x5e], "ー":[0x81,0x5b],
  "上":[0x8f,0xe3], "下":[0x89,0xba], "全":[0x91,0x53], "半":[0x94,0xbc], "身":[0x90,0x67],
  "左":[0x8d,0xb6], "右":[0x89,0x45], "手":[0x8e,0xe8], "首":[0x8e,0xf1], "肩":[0x8c,0xa8],
  "腕":[0x98,0x72], "足":[0x91,0xab], "頭":[0x93,0xaa], "親":[0x90,0x65],
  "ひ":[0x82,0xd0], "じ":[0x82,0xb6], "ざ":[0x82,0xb4]
};
function sjisFix(str, len) {
  const out = new Uint8Array(len);
  let i = 0;
  for (const ch of String(str)) {
    const code = ch.charCodeAt(0);
    const bytes = code < 0x80 ? [code] : SJIS[ch];
    if (!bytes || i + bytes.length > len) continue;
    for (const b of bytes) out[i++] = b;
  }
  return out;
}
const VMD_LINEAR = [0, 0, 127, 127];      // 補間なし＝直線（64バイトを同じ模様で埋めて、どの読み方でも直線になるように）
function buildVmd(frames, modelName = "trk") {
  const n = frames.length, size = 30 + 20 + 4 + n * 111 + 20;
  const buf = new ArrayBuffer(size), u8 = new Uint8Array(buf), dv = new DataView(buf);
  const header = "Vocaloid Motion Data 0002";
  for (let i = 0; i < header.length; i++) u8[i] = header.charCodeAt(i);
  u8.set(sjisFix(modelName, 20), 30);
  dv.setUint32(50, n, true);
  frames.forEach((f, i) => {
    const at = 54 + i * 111;
    u8.set(sjisFix(f.bone, 15), at);
    dv.setUint32(at + 15, f.frame, true);
    dv.setFloat32(at + 19, f.pos[0], true); dv.setFloat32(at + 23, f.pos[1], true); dv.setFloat32(at + 27, f.pos[2], true);
    dv.setFloat32(at + 31, f.rot[0], true); dv.setFloat32(at + 35, f.rot[1], true);
    dv.setFloat32(at + 39, f.rot[2], true); dv.setFloat32(at + 43, f.rot[3], true);
    for (let k = 0; k < 64; k++) u8[at + 47 + k] = VMD_LINEAR[k % 4];
  });
  let at = 54 + n * 111;                  // モーフ・カメラ・照明・セルフシャドウ・プロパティは 0 件
  for (let k = 0; k < 5; k++) { dv.setUint32(at, 0, true); at += 4; }
  return new Uint8Array(buf);
}
/* 回転（ラジアン）→ クォータニオン。かけ算は Y → Z → X の順で統一します */
const DEG = Math.PI / 180;
function qAxis(x, y, z, deg) {
  const h = deg * DEG / 2, s = Math.sin(h);
  return [x * s, y * s, z * s, Math.cos(h)];
}
function qMul(a, b) {
  return [
    a[3] * b[0] + a[0] * b[3] + a[1] * b[2] - a[2] * b[1],
    a[3] * b[1] - a[0] * b[2] + a[1] * b[3] + a[2] * b[0],
    a[3] * b[2] + a[0] * b[1] - a[1] * b[0] + a[2] * b[3],
    a[3] * b[3] - a[0] * b[0] - a[1] * b[1] - a[2] * b[2]
  ];
}
const qEuler = (rx, ry, rz) => qMul(qMul(qAxis(0, 1, 0, ry), qAxis(0, 0, 1, rz)), qAxis(1, 0, 0, rx));
const FPS = 30, STEP = 3;                 // MMDのモーションは 30fps。3フレームごとに置く
/* モーションの台本：t（秒）→ 各ボーンの回転・位置。ここが「振り付け」です */
const BUILTIN = {
  step: { label:"mmdMotionStep", bpm:120, seconds:4, pose:t => {
    const w = 2 * Math.PI * t * 2, slow = 2 * Math.PI * t;
    return {
      "センター": { pos:[0, -0.5 * Math.max(0, Math.sin(w)), 0], rot:[0, 0, 0] },
      "上半身": { rot:[0, 4 * Math.sin(slow), 0] },
      "首":    { rot:[2 * Math.sin(w), -3 * Math.sin(slow), 0] },
      "左腕":  { rot:[0, 0, -55 + 32 * Math.sin(w)] },
      "右腕":  { rot:[0, 0, 55 - 32 * Math.sin(w)] },
      "左ひじ":{ rot:[0, -18 - 10 * Math.sin(w), 0] },
      "右ひじ":{ rot:[0, 18 + 10 * Math.sin(w), 0] }
    };
  } },
  swing: { label:"mmdMotionSwing", bpm:100, seconds:6, pose:t => {
    const w = 2 * Math.PI * t / 1.5, slow = 2 * Math.PI * t / 3;
    return {
      "センター": { pos:[0.25 * Math.sin(w), -0.12 * Math.max(0, Math.sin(w * 2)), 0], rot:[0, 0, 3 * Math.sin(w)] },
      "上半身": { rot:[0, 7 * Math.sin(slow), 2 * Math.sin(w)] },
      "上半身2":{ rot:[0, 4 * Math.sin(slow + 1), 0] },
      "首":    { rot:[3 * Math.sin(w + 1), -5 * Math.sin(slow), 0] },
      "左腕":  { rot:[0, 0, -28 + 16 * Math.sin(w + 0.6)] },
      "右腕":  { rot:[0, 0, 28 - 16 * Math.sin(w - 0.6)] },
      "左ひじ":{ rot:[0, -22, 0] }, "右ひじ":{ rot:[0, 22, 0] }
    };
  } },
  turn: { label:"mmdMotionTurn", bpm:120, seconds:4, pose:t => {
    const w = 2 * Math.PI * t / 2, spin = 360 * (t / 4), rise = Math.sin(Math.PI * Math.min(1, t / 4));
    return {
      "センター": { pos:[0, 0.5 * rise, 0], rot:[0, spin, 0] },
      "上半身": { rot:[-6 * rise, 0, 0] },
      "首":    { rot:[-4 * rise, 6 * Math.sin(w), 0] },
      "左腕":  { rot:[0, 0, -78 * rise - 10] },
      "右腕":  { rot:[0, 0, 78 * rise + 10] },
      "左ひじ":{ rot:[0, -10, 0] }, "右ひじ":{ rot:[0, 10, 0] }
    };
  } }
};
const builtinBytes = id => {
  const m = BUILTIN[id];
  if (!m) return null;
  const frames = [];
  for (let f = 0; f <= m.seconds * FPS; f += STEP) {
    const t = f / FPS, pose = m.pose(t);
    for (const bone of Object.keys(pose)) {
      const b = pose[bone], rot = qEuler(b.rot[0], b.rot[1], b.rot[2]);
      frames.push({ bone, frame:f, pos:b.pos || [0, 0, 0], rot });
    }
  }
  return buildVmd(frames, "trk-builtin-" + id);
};

/* ============ 状態 ============ */
const canvas = $("mmdCanvas"), prev = $("mmdPreview"), pctx = prev && prev.getContext("2d");
let renderer = null, scene = null, camera = null, pivot = null;
let L = null, injected = null;                     // L = { THREE, ThreeMmdLoader, createMmdFileIndex }
let model = null, modelFiles = [], modelName = "", modelKey = "";
let anim = null, motionKind = "none", motionName = "", motionDur = 0;
let frameInfo = null, fitScale = 1, lastT = 0, curKey = "", playing = false, clock = 0;

/* ---------- 3Dの部品は、必要になったときだけ（テストでは差し替えできます） ---------- */
function libs() {
  if (injected) return Promise.resolve(injected);
  if (!L) {
    L = Promise.all([import("three"), import(MMD_LIB)])
      .then(([THREE, M]) => ({ THREE, ThreeMmdLoader:M.ThreeMmdLoader, createMmdFileIndex:M.createMmdFileIndex }))
      .catch(e => { L = null; throw e; });
  }
  return L;
}

/* ---------- 画面まわり（vrm.js と同じ考え方） ---------- */
function ensureScene() {
  if (renderer && scene && camera && pivot) return true;
  const { THREE } = L;
  /* 途中で失敗した半端な状態を残さない（つぎの読み込みが壊れないように） */
  try {
    const r = new THREE.WebGLRenderer({ canvas, alpha:true, antialias:true });
    r.setClearColor(0x000000, 0);
    const sc = new THREE.Scene();
    const cam = new THREE.PerspectiveCamera(30, 1, 0.05, 60);
    const light = new THREE.DirectionalLight(0xffffff, 1.7);
    light.position.set(0.4, 1, 1.6).normalize(); sc.add(light);
    sc.add(new THREE.AmbientLight(0xffffff, 0.85));
    const back = new THREE.DirectionalLight(0xbfd4ff, 0.5);
    back.position.set(-0.6, 0.5, -1).normalize(); sc.add(back);
    const pv = new THREE.Group(); sc.add(pv);
    renderer = r; scene = sc; camera = cam; pivot = pv;
    return true;
  } catch (e) { console.error(e); renderer = null; scene = null; camera = null; pivot = null; return false; }
}
function measure() {
  const { THREE } = L;
  scene.updateMatrixWorld(true);
  const box = new THREE.Box3().setFromObject(model.root);
  const h = Math.max(0.01, box.max.y - box.min.y);
  fitScale = 1.6 / h;                              // 画面のなかで 1.6 の高さに合わせる
  frameInfo = { minY:box.min.y, maxY:box.max.y, headY:box.min.y + h * 0.92 };
  applyModelTransform();
}
function applyModelTransform() {
  if (!model || !frameInfo) return;
  const sc = fitScale * (settings.mmdScale || 1);
  model.root.scale.setScalar(sc);
  model.root.position.y = -frameInfo.minY * sc;
  pivot.rotation.y = (settings.mmdTurn || 0) * DEG;
  frameCamera();
}
function frameCamera() {
  if (!frameInfo || !camera || !L) return;
  const h = Math.max(0.3, frameInfo.maxY - frameInfo.minY) * (settings.mmdScale || 1);
  const fh = 1.6 * (settings.mmdScale || 1) * 1.15, cy = fh * 0.52;
  const d = (fh / 2) / Math.tan(L.THREE.MathUtils.degToRad(camera.fov) / 2);
  camera.position.set(0, cy, d); camera.lookAt(0, cy, 0);
}
function applyRect() {
  if (!renderer || !camera) return;
  const R = mmdRect(), sc = Math.min(innerWidth / 1920, innerHeight / 1080);
  const pr = Math.min(2, Math.max(0.5, (devicePixelRatio || 1) * sc));
  const key = `${R.x},${R.y},${R.w},${R.h},${pr.toFixed(2)}`;
  if (key === curKey) return;
  curKey = key;
  Object.assign(canvas.style, { left:R.x + "px", top:R.y + "px", width:R.w + "px", height:R.h + "px" });
  renderer.setPixelRatio(pr); renderer.setSize(R.w, R.h, false);
  camera.aspect = R.w / R.h; camera.updateProjectionMatrix(); frameCamera();
}
function disposeModel() {
  if (!model) return;
  try {
    pivot.remove(model.root);
    const { THREE } = L;
    model.root.traverse(o => {
      if (o.geometry && o.geometry.dispose) o.geometry.dispose();
      const mats = Array.isArray(o.material) ? o.material : (o.material ? [o.material] : []);
      for (const m of mats) { for (const k of ["map", "alphaMap", "toonMap", "gradientMap"]) if (m[k] && m[k].dispose) m[k].dispose(); if (m.dispose) m.dispose(); }
    });
    if (THREE && THREE.Cache) { /* テクスチャは上の traverse で破棄済み */ }
  } catch (e) { console.error(e); }
  model = null; frameInfo = null; modelKey = "";
}

/* ============ モデルの読み込み ============ */
function pickMain(files) {
  const models = files.filter(f => isMmdFile(f.name));
  if (!models.length) return null;
  const shaped = models.find(f => /\.pmx$/i.test(f.name)) || models[0];
  const root = shaped.webkitRelativePath ? shaped.webkitRelativePath.split("/").slice(0, -1).join("/") : "";
  /* いちばん浅い場所にある .pmx を本命にする（フォルダ直下のモデル） */
  return models.slice().sort((a, b) => {
    const da = (a.webkitRelativePath || a.name).split("/").length, db = (b.webkitRelativePath || b.name).split("/").length;
    return da - db;
  })[0] || shaped;
}
async function doLoadModel(files, { restored = false, select = true, save = true } = {}) {
  if (!files || !files.length) { status("mmdFilesEmpty"); return; }
  if (files.length > MAX_FILES) { status("mmdTooManyFiles", { n:MAX_FILES }); return; }
  const main = pickMain(files);
  if (!main) { status("mmdNotMmd"); return; }
  if (main.size > MAX_PMX) { status("mmdTooBig", { n:120, m:40 }); return; }
  status("mmdLoading");
  try {
    try { L = await libs(); } catch (_) { throw fail("mmdNetError"); }
    if (!ensureScene()) throw fail("mmdNoWebGL");
    const idx = L.createMmdFileIndex ? L.createMmdFileIndex(files) : null;
    const textureResolver = idx ? { resolve: async path => {
      const p = String(path || "").replace(/\\/g, "/");
      return idx.resolve(p) || idx.resolve(p.replace(/^\.\//, "")) || idx.resolve(p.split("/").pop()) || undefined;
    } } : undefined;
    const loader = new L.ThreeMmdLoader(textureResolver ? { textureResolver } : undefined);
    const next = await loader.loadModel(main, { outline:true });
    if (!next || !next.root) throw fail("mmdLoadError");
    if (!pivot) throw fail("mmdNoWebGL");
    disposeModel();
    model = next; modelFiles = files; modelName = String(main.name).replace(/\.(pmx|pmd)$/i, "").slice(0, 60);
    pivot.add(model.root);
    model.root.traverse(o => { o.frustumCulled = false; });
    measure();
    await applyMotion(motionKind, { silent:true, fromRestore:true });
    status(restored ? "mmdRestored" : "mmdLoaded", { name:modelName });
    if (select) selectMmdMascot();
    if (save && !restored && settings.mmdRemember) {
      const keep = files.filter(f => f.size < 60 * MB).slice(0, MAX_FILES);
      await mmdDB.put("model", { files:keep, main:main.name, name:modelName, savedAt:Date.now() })
        .catch(() => status("mmdSaveFail"));
    }
  } catch (e) {
    console.error(e);
    status(e && e.key ? e.key : "mmdLoadError");
  }
}
const loadModelFiles = (files, opts) => enqueue(() => doLoadModel(files, opts));

/* ============ モーション ============ */
async function applyMotion(kind, { silent = false, fromRestore = false } = {}) {
  motionKind = kind || "none";
  if (!model) return;
  try {
    if (motionKind === "none") { anim = null; motionDur = 0; motionName = ""; }
    else if (BUILTIN[motionKind]) {
      const bytes = builtinBytes(motionKind);
      anim = await newAnimLoader().loadAnimation(bytes);
      motionDur = BUILTIN[motionKind].seconds; motionName = tr(BUILTIN[motionKind].label);
    } else if (motionKind === "file") {
      const rec = await mmdDB.get("motion");
      const file = (motionFiles && motionFiles[0]) || (rec && rec.file);
      if (!file) { motionKind = "none"; anim = null; motionDur = 0; return; }
      if (file.size > MAX_VMD) { status("mmdTooBig", { n:120, m:40 }); return; }
      anim = await newAnimLoader().loadAnimation(file);
      const frames = (anim && anim.animation && anim.animation.metadata && anim.animation.metadata.maxFrame) || 0;
      motionDur = Math.max(0.5, frames / FPS); motionName = String(file.name).replace(/\.vmd$/i, "").slice(0, 60);
    }
    if (anim && model.setAnimation) model.setAnimation(anim);
    if (!fromRestore && !silent && motionKind === "file") status("mmdVmdLoaded", { name:motionName });
  } catch (e) {
    console.error(e);
    anim = null; motionDur = 0;
    if (motionKind === "file") { motionKind = "none"; status("mmdVmdBad"); }
  }
  renderMotionList();
}
function newAnimLoader() { return new L.ThreeMmdLoader(); }
let motionFiles = null;
async function doLoadMotion(file, { restored = false } = {}) {
  if (!file) return;
  if (!isVmdFile(file.name)) { status("mmdVmdBad"); return; }
  if (file.size > MAX_VMD) { status("mmdTooBig", { n:120, m:40 }); return; }
  if (!model) { status("mmdNoModel"); return; }
  try { L = await libs(); } catch (_) { status("mmdNetError"); return; }
  motionFiles = [file];
  await applyMotion("file", { fromRestore:restored });
  if (!restored && settings.mmdRemember) await mmdDB.put("motion", { file, name:file.name, savedAt:Date.now() }).catch(() => {});
  renderMotionList();
}
const loadMotionFile = (file, opts) => enqueue(() => doLoadMotion(file, opts));

/* ============ 姿勢とBPM（毎フレーム） ============ */
/* モーションの速さ：曲のBPM ÷ モーションの基準BPM（どちらかが0なら 1） */
function motionRate() {
  const mb = settings.mmdMotionBpm || 0, sb = (typeof chartMeta !== "undefined" && chartMeta && chartMeta.bpm) || 0;
  return (mb && sb) ? Math.min(3, Math.max(0.25, sb / mb)) : 1;
}
function pose(time) {
  if (!model) return;
  const rate = motionRate();
  const t = motionDur ? (time * rate) % motionDur : (time * rate);
  try { model.update(t); } catch (e) { console.error(e); }
}

/* ============ 描画ループ（必要なときだけ描く） ============ */
function animate(now) {
  requestAnimationFrame(animate);
  playing = !!model && phase !== "title" && activeMascot() === "mmd";
  canvas.hidden = !playing;
  const panel = $("mmdPanel");
  const previewOn = !!model && phase === "title" && screen === "settings" && !!panel && panel.open && !!prev;
  if (!playing && !previewOn) { lastT = now; return; }
  const dt = Math.min(0.1, Math.max(0.001, (now - lastT) / 1000)); lastT = now;
  try {
    applyRect(); applyModelTransform();
    clock += dt;
    pose(clock);
    if (renderer && scene && camera) renderer.render(scene, camera);
    if (previewOn && pctx) {
      pctx.clearRect(0, 0, prev.width, prev.height);
      const a = canvas.width / canvas.height, dh = prev.height, dw = dh * a;
      pctx.drawImage(canvas, (prev.width - dw) / 2, 0, dw, dh);
    }
  } catch (e) { console.error(e); }
}
requestAnimationFrame(animate);

/* ============ 画面の組み立て ============ */
function setAgreeUI() {
  const on = !!settings.mmdAgreed;
  for (const id of ["mmdModelFile", "mmdFolderFile", "mmdMotionFile"]) {
    const inp = $(id); if (inp) inp.disabled = !on;
    const lab = inp && inp.closest("label"); if (lab) lab.classList.toggle("disabled", !on);
  }
}
function selectMmdMascot() { settings.mascot = "mmd"; saveUserPrefs(); updateMascotUI(); status("mmdSelected"); }
function renderMotionList() {
  const sel = $("mmdMotionSelect");
  if (!sel) return;
  const keep = motionKind;
  sel.textContent = "";
  const opt = document.createElement("option"); opt.value = "none"; opt.textContent = tr("mmdMotionNone"); sel.append(opt);
  for (const id of Object.keys(BUILTIN)) {
    const o = document.createElement("option"); o.value = id; o.textContent = tr(BUILTIN[id].label); o.dataset.builtin = "1"; sel.append(o);
  }
  if (anim && keep === "file") { const o = document.createElement("option"); o.value = "file"; o.textContent = "🎬 " + (motionName || "VMD"); sel.append(o); }
  sel.value = (keep === "file" && !anim) ? "none" : keep;
}
function syncUI() {
  const box = $("mmdInfo");
  if (box) {
    box.textContent = "";
    const add = (k, v) => { const d = el("div", "", `${tr(k)}: ${v}`); box.append(d); };
    if (modelName) add("mmdModelHead", modelName);
    if (motionName) add("mmdMotionHead", motionName);
    if (!modelName && !motionName) box.append(el("div", "hint", tr("mmdHint")));
  }
  const size = $("mmdSize"), sizeVal = $("mmdSizeVal");
  if (size) { size.value = settings.mmdScale; if (sizeVal) sizeVal.textContent = Math.round(settings.mmdScale * 100) + "%"; }
  const turn = $("mmdTurn"), turnVal = $("mmdTurnVal");
  if (turn) { turn.value = settings.mmdTurn; if (turnVal) turnVal.textContent = settings.mmdTurn + "°"; }
  const mb = $("mmdBpm"); if (mb) mb.value = settings.mmdMotionBpm;
  const cr = $("mmdCredit"); if (cr && document.activeElement !== cr) cr.value = settings.mmdCredit || "";
  const rem = $("mmdRemember"); if (rem) rem.checked = settings.mmdRemember !== false;
  const ag = $("mmdAgree"); if (ag) ag.checked = !!settings.mmdAgreed;
  setAgreeUI(); renderMotionList();
}

addEventListener("DOMContentLoaded", () => {
  if (!canvas || !$("mmdPanel")) return;

  $("mmdAgree").addEventListener("change", e => {
    settings.mmdAgreed = !!e.target.checked; saveUserPrefs(); setAgreeUI();
    if (settings.mmdAgreed) status("mmdHint"); else status("mmdNoAgree");
  });
  $("mmdModelFile").addEventListener("change", e => {
    const f = e.target.files && e.target.files[0]; e.target.value = "";
    if (!f) return;
    if (!settings.mmdAgreed) { status("mmdNoAgree"); return; }
    if (!isMmdFile(f.name)) { status("mmdNotMmd"); return; }
    motionFiles = null;
    loadModelFiles([f]);
  });
  $("mmdFolderFile").addEventListener("change", e => {
    const files = [...(e.target.files || [])]; e.target.value = "";
    if (!settings.mmdAgreed) { status("mmdNoAgree"); return; }
    if (!files.length) { status("mmdFilesEmpty"); return; }
    motionFiles = null;
    loadModelFiles(files);
  });
  $("mmdMotionFile").addEventListener("change", e => {
    const f = e.target.files && e.target.files[0]; e.target.value = "";
    if (!f) return;
    if (!settings.mmdAgreed) { status("mmdNoAgree"); return; }
    loadMotionFile(f);
  });
  $("mmdMotionSelect").addEventListener("change", e => loadMotionKind(e.target.value));
  $("mmdClearModel").addEventListener("click", () => {
    disposeModel(); motionKind = "none"; anim = null; motionDur = 0; motionName = "";
    canvas.hidden = true; motionFiles = null;
    mmdDB.del("model").catch(() => {}); mmdDB.del("motion").catch(() => {});
    syncUI(); status("mmdClearModel");
  });
  $("mmdClearMotion").addEventListener("click", () => {
    motionFiles = null; motionKind = "none"; anim = null; motionDur = 0; motionName = "";
    mmdDB.del("motion").catch(() => {});
    syncUI(); status("mmdClearMotion");
  });
  $("mmdSize").addEventListener("input", e => { settings.mmdScale = Number(e.target.value) || 1; $("mmdSizeVal").textContent = Math.round(settings.mmdScale * 100) + "%"; });
  $("mmdSize").addEventListener("change", () => saveUserPrefs());
  $("mmdTurn").addEventListener("input", e => { settings.mmdTurn = Number(e.target.value) || 0; $("mmdTurnVal").textContent = settings.mmdTurn + "°"; });
  $("mmdTurn").addEventListener("change", () => saveUserPrefs());
  $("mmdBpm").addEventListener("change", e => { settings.mmdMotionBpm = Math.max(0, Math.min(300, Number(e.target.value) || 0)); saveUserPrefs(); });
  $("mmdCredit").addEventListener("input", e => { settings.mmdCredit = String(e.target.value).slice(0, 120); });
  $("mmdCredit").addEventListener("change", () => saveUserPrefs());
  $("mmdRemember").addEventListener("change", e => {
    settings.mmdRemember = !!e.target.checked; saveUserPrefs();
    if (!settings.mmdRemember) { mmdDB.del("model").catch(() => {}); mmdDB.del("motion").catch(() => {}); }
  });

  on("language", () => { syncUI(); });

  /* 前回のモデルを戻す（覚える設定のときだけ・セーフモードでは何もしない） */
  syncUI();
  if (safeNow()) { status("mmdSafe"); return; }
  if (settings.mmdRemember) enqueue(async () => {
    try {
      const rec = await mmdDB.get("model");
      if (rec && rec.files && rec.files.length) {
        settings.mmdAgreed = true; syncUI();
        await doLoadModel(rec.files, { restored:true, select:false, save:false });
        const m = await mmdDB.get("motion");
        if (m && m.file) await doLoadMotion(m.file, { restored:true });
      }
    } catch (_) {}
  });
});

function loadMotionKind(kind) {
  if (kind === "file" && !motionFiles) {
    const rec = mmdDB.get("motion").catch(() => null);
    enqueue(async () => { const r = await rec; if (r && r.file) { motionFiles = [r.file]; await applyMotion("file"); } else { renderMotionList(); } });
    return;
  }
  enqueue(() => applyMotion(kind));
}

/* ============ 窓口（テスト・コンソールから） ============ */
window.TrkMMD = {
  version: 1,
  lib: MMD_LIB,
  key: "shadow_taiko_mmd",
  /* テスト用：3Dの部品を差し替える（本番では使いません） */
  _injectLibs(fake) { injected = fake; L = fake; },
  _builtin: id => builtinBytes(id),
  _sjis: (s, n) => Array.from(sjisFix(s, n)),
  builtins: () => Object.keys(BUILTIN),
  motions: () => Object.entries(BUILTIN).map(([id, m]) => ({ id, bpm:m.bpm, seconds:m.seconds })),
  model: () => model ? { name:modelName, files:modelFiles.length } : null,
  motion: () => ({ kind:motionKind, name:motionName, duration:motionDur, anim:!!anim }),
  setMotion: kind => loadMotionKind(kind),
  loadModel: files => loadModelFiles(Array.isArray(files) ? files : [files]),
  loadMotion: file => loadMotionFile(file),
  clear: () => { disposeModel(); anim = null; motionKind = "none"; motionDur = 0; motionName = ""; canvas.hidden = true; },
  select: selectMmdMascot,
  isPlaying: () => playing,
  clock: () => clock,
  rate: motionRate,
  info: () => ({ model:modelName, motion:motionName, kind:motionKind, dur:motionDur, scale:settings.mmdScale, turn:settings.mmdTurn, agreed:!!settings.mmdAgreed })
};
})();
/* ✅ mmd.js 完了 */
